#  Setup and loading the data




In [0]:
#Load the libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import nltk

In [0]:
#importing the training data
imdb_data=pd.read_csv('IMDB Dataset.csv')
print(imdb_data.shape)
imdb_data.head(10)

(50000, 2)


review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1
5  Probably my all-time favorite movie, a story o...          1
6  I sure would like to see a resurrection of a u...          1
7  This show was an amazing, fresh & innovative i...          0
8  Encouraged by the positive comments about this...          0
9  If you like original gut wrenching laughter yo...          1

In [0]:
#sentiment count
imdb_data['sentiment'].value_counts()

1    25000
0    25000
Name: sentiment, dtype: int64

# Preprocessing including stopwords, punctuations, tokenization, stemming...

In [0]:
# Setup for stopwords
!pip install -q wordcloud
import wordcloud

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from wordcloud import WordCloud,STOPWORDS
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize,sent_tokenize
from bs4 import BeautifulSoup
import spacy
import re,string,unicodedata
from nltk.tokenize.toktok import ToktokTokenizer
from nltk.stem import LancasterStemmer,WordNetLemmatizer
from sklearn.linear_model import LogisticRegression,SGDClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from textblob import TextBlob
from textblob import Word
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger') 

import matplotlib.pyplot as plt
import io
import unicodedata

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


In [0]:
#Tokenization of text
tokenizer=ToktokTokenizer()
stopword_list=nltk.corpus.stopwords.words("english")

In [0]:

def strip_html(text):
    soup = BeautifulSoup(text, "html.parser")
    return soup.get_text()
def remove_between_square_brackets(text):
    return re.sub('\[[^]]*\]', '', text)
def denoise_text(text):
    text = strip_html(text)
    text = remove_between_square_brackets(text)
    return text
imdb_data['review']=imdb_data['review'].apply(denoise_text)

In [0]:
def remove_special_characters(text, remove_digits=True):
    pattern=r'[^a-zA-z0-9\s]'
    text=re.sub(pattern,'',text)
    return text

imdb_data['review']=imdb_data['review'].apply(remove_special_characters)

In [0]:
#Stemming the text
def simple_stemmer(text):
    ps=nltk.porter.PorterStemmer()
    text= ' '.join([ps.stem(word) for word in text.split()])
    return text

imdb_data['review']=imdb_data['review'].apply(simple_stemmer)

In [0]:
stop=set(stopwords.words('english'))
print(stop)

#removing the stopwords
def remove_stopwords(text, is_lower_case=False):
    tokens = tokenizer.tokenize(text)
    tokens = [token.strip() for token in tokens]
    if is_lower_case:
        filtered_tokens = [token for token in tokens if token not in stopword_list]
    else:
        filtered_tokens = [token for token in tokens if token.lower() not in stopword_list]
    filtered_text = ' '.join(filtered_tokens)    
    return filtered_text
#Apply function on review column
imdb_data['review']=imdb_data['review'].apply(remove_stopwords)

{'nor', 'which', 'same', 'can', 'your', 'does', 'her', 'how', "doesn't", 'hasn', 'it', "needn't", 'as', 'his', 'will', 'above', 'then', 'hers', 'below', "mustn't", "isn't", 'over', "it's", 'between', 'myself', 'hadn', 'most', 'yourselves', 'had', 'm', "won't", 'don', 'own', 'an', 'after', 'was', 'again', 'being', 'you', 'who', 'aren', 'against', 'further', 'up', 'this', 'll', 're', 'isn', "she's", 'i', 'here', 'wouldn', 'such', 'when', 'only', 'where', "hadn't", 'didn', 'any', "mightn't", 'that', 'now', 'did', 'herself', 'into', 'other', 'are', 'y', "aren't", 'doesn', 'been', 'am', 'all', 'during', 'before', 'while', 'out', 'my', 'a', "should've", 'o', 'so', 'our', "shouldn't", 'more', 'himself', 'off', 'from', "you'd", 'do', 'too', 'needn', "shan't", "weren't", 'shouldn', "you're", "wasn't", "don't", 'each', 'doing', 'itself', 'shan', 'their', 'few', 'wasn', 'them', 'she', 'the', 'him', 'once', 'of', 'at', 'its', 'should', 'those', 'has', 'on', 'to', 'mightn', 'ain', 'weren', 'both', 

In [0]:
imdb_data.head(10)

review  sentiment
0  one review ha mention watch 1 Oz episod youll ...          1
1  wonder littl product film techniqu veri unassu...          1
2  thought thi wa wonder way spend time hot summe...          1
3  basic famili littl boy jake think zombi hi clo...          0
4  petter mattei love time money visual stun film...          1
5  probabl alltim favorit movi stori selfless sac...          1
6  sure would like see resurrect date seahunt ser...          1
7  thi show wa amaz fresh innov idea 70 first air...          0
8  encourag posit comment thi film wa look forwar...          0
9  like origin gut wrench laughter like thi movi ...          1

# Export the dataframe into a csv file

In [0]:
#Export the dataframe to csv file for further exploration 
imdb_data.to_csv('IMDB Dataset_preprocessed.csv',index=False)
from google.colab import files
files.download('IMDB Dataset_preprocessed.csv')

# Split the data to 25000:25000

In [0]:
#split the dataset  
#train dataset
train_reviews=imdb_data.review[:25000]
train_sentiments=imdb_data.sentiment[:25000]
#test dataset
test_reviews=imdb_data.review[25000:]
test_sentiments=imdb_data.sentiment[25000:]
print(train_reviews.shape,train_sentiments.shape)
print(test_reviews.shape,test_sentiments.shape)

(25000,) (25000,)
(25000,) (25000,)


In [0]:
norm_train_reviews=imdb_data.review[:25000]
norm_test_reviews=imdb_data.review[25000:]

# Build the matrix/vectorizer for Bag of Words, TF-IDF

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelBinarizer
cv=CountVectorizer(min_df=0,max_df=1,binary=False,ngram_range=(1,3))
#transformed train reviews
cv_train_reviews=cv.fit_transform(norm_train_reviews)
#transformed test reviews
cv_test_reviews=cv.transform(norm_test_reviews)

print('BOW_cv_train:',cv_train_reviews.shape)
print('BOW_cv_test:',cv_test_reviews.shape)

BOW_cv_train: (25000, 4121608)
BOW_cv_test: (25000, 4121608)


In [0]:
#Tfidf vectorizer
tv=TfidfVectorizer(min_df=0,max_df=1,use_idf=True,ngram_range=(1,3))
#transformed train reviews
tv_train_reviews=tv.fit_transform(norm_train_reviews)
#transformed test reviews
tv_test_reviews=tv.transform(norm_test_reviews)
print('Tfidf_train:',tv_train_reviews.shape)
print('Tfidf_test:',tv_test_reviews.shape)

Tfidf_train: (25000, 4121608)
Tfidf_test: (25000, 4121608)


In [0]:
#labeling the sentient data
lb=LabelBinarizer()
#transformed sentiment data
sentiment_data=lb.fit_transform(imdb_data['sentiment'])
print(sentiment_data.shape)
#Spliting the sentiment data
train_sentiments=sentiment_data[:25000]
test_sentiments=sentiment_data[25000:]
print(train_sentiments)
print(test_sentiments)

(50000, 1)
[[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [0]]
[[0]
 [0]
 [1]
 ...
 [0]
 [0]
 [0]]


# Build the logistic regression model

In [0]:
lr=LogisticRegression(penalty='l2',max_iter=500,C=1,random_state=42)
lr_bow=lr.fit(cv_train_reviews,train_sentiments)
print(lr_bow)
lr_tfidf=lr.fit(tv_train_reviews,train_sentiments)
print(lr_tfidf)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=500,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=500,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)


# Do the prediction, get the report and confusion matrix

In [0]:
#Predicting the model for bag of words
lr_bow_predict=lr_bow.predict(cv_test_reviews)
print(lr_bow_predict)
#Predicting the model for tfidf features
lr_tfidf_predict=lr_tfidf.predict(tv_test_reviews)
print(lr_tfidf_predict)

[0 0 1 ... 0 0 0]
[0 0 1 ... 0 0 0]


In [0]:
#Classification report for bag of words 
lr_bow_report=classification_report(test_sentiments,lr_bow_predict,target_names=['Positive','Negative'])
print(lr_bow_report)

#Classification report for tfidf features
lr_tfidf_report=classification_report(test_sentiments,lr_tfidf_predict,target_names=['Positive','Negative'])
print(lr_tfidf_report)
#confusion matrix for bag of words
cm_bow=confusion_matrix(test_sentiments,lr_bow_predict,labels=[1,0])
print(cm_bow)
#confusion matrix for tfidf features
cm_tfidf=confusion_matrix(test_sentiments,lr_tfidf_predict,labels=[1,0])
print(cm_tfidf)

              precision    recall  f1-score   support

    Positive       0.73      0.75      0.74     12474
    Negative       0.74      0.73      0.73     12526

    accuracy                           0.74     25000
   macro avg       0.74      0.74      0.74     25000
weighted avg       0.74      0.74      0.74     25000

              precision    recall  f1-score   support

    Positive       0.71      0.78      0.74     12474
    Negative       0.76      0.69      0.72     12526

    accuracy                           0.73     25000
   macro avg       0.74      0.73      0.73     25000
weighted avg       0.74      0.73      0.73     25000

[[9088 3438]
 [3159 9315]]
[[8626 3900]
 [2766 9708]]


# KNN and Kmeans

In [0]:
import skimage
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow import keras
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans
from collections import Counter

In [0]:
# Clustering the document with KNN classifier
modelknn = KNeighborsClassifier(n_neighbors=1)
modelknn.fit(cv_train_reviews,train_sentiments)

# Clustering the trainings with K-means technique
modelkmeans = KMeans(n_clusters=2, init='random', max_iter=200, n_init=10)
modelkmeans.fit(cv_train_reviews)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


KMeans(algorithm='auto', copy_x=True, init='random', max_iter=200, n_clusters=2,
       n_init=10, n_jobs=None, precompute_distances='auto', random_state=None,
       tol=0.0001, verbose=0)

In [0]:
#Predicting the models for tfidf features
knn_tfidf_predict=modelknn.predict(tv_test_reviews)
print(knn_tfidf_predict)

kmeans_tfidf_predict=modelkmeans.predict(tv_test_reviews)
print(kmeans_tfidf_predict)

[0 0 0 ... 0 0 0]
[1 1 1 ... 1 1 1]


In [0]:
#Classification report for knn 
knn_tfidf_report=classification_report(test_sentiments,knn_tfidf_predict,target_names=['Positive','Negative'])
print(knn_tfidf_report)
#Classification report for keams
kmeans_tfidf_report=classification_report(test_sentiments,kmeans_tfidf_predict,target_names=['Positive','Negative'])
print(kmeans_tfidf_report)

#confusion matrix for knn
cm_knn=confusion_matrix(test_sentiments,knn_tfidf_predict,labels=[1,0])
print(cm_knn)
#confusion matrix for kmeans
cm_kmeans=confusion_matrix(test_sentiments,kmeans_tfidf_predict,labels=[1,0])
print(cm_kmeans)

              precision    recall  f1-score   support

    Positive       0.50      1.00      0.67     12474
    Negative       0.00      0.00      0.00     12526

    accuracy                           0.50     25000
   macro avg       0.25      0.50      0.33     25000
weighted avg       0.25      0.50      0.33     25000

              precision    recall  f1-score   support

    Positive       0.00      0.00      0.00     12474
    Negative       0.50      1.00      0.67     12526

    accuracy                           0.50     25000
   macro avg       0.25      0.50      0.33     25000
weighted avg       0.25      0.50      0.33     25000

[[    0 12526]
 [    0 12474]]
[[12526     0]
 [12474     0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
# df2 = pd.DataFrame(np.array([["I love this movie A masterful production about one of the great master's of comedy and his life.", 1], ["worst movie i have ever seen", 0]]),
#                    columns=['review', 'sentiment'])
# df2['review']=df2['review'].apply(remove_special_characters)
# df2['review']=df2['review'].apply(simple_stemmer)
# df2['review']=df2['review'].apply(remove_stopwords)
# print(df2)
# tv_test=tv.fit_transform(df2)
# print('Tfidf_train:',tv_test.shape)